language: node_js
node_js:
  - "8.9"

script: 'true'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
  - ftomi89@gmail.com
  - dottoska.96@gmail.com
  - tibor.m.horvath@gmail.com
  - kolicalc@yahoo.com
deploy:
  provider: heroku
  api_key:
    secure: N4K/HkbhYv/CsMScNcxChfg7Vxd0pYaQC5P6EXT9hC+TrL60b7Zj4AuWKfdqe1o5yNid6bxWWSn4dZ4Hl9G3niboGt8zVTL3suDKDkxD5zLRwP07UO6ACoexzWYG2fuDykuEbaj3dBPXRErp2wb8FLiP3x02LksNVkebnh7teEzOd1/OtFHeCrVYahi4Kh/YpADtHX7VgJnnWkdchALGFlkhKi39ZG7alMVHQnkrmKfxxXRfdvU1CNacgGySPGauxPubMuodjJ4nSfPot+8e2uL00V2J80s6j2wQaMZieawbZR1atH59McG0xrUzVkGJr/OrKNosAvdINvpZuQ+98qoBIQdtxj3/80BsBTnnz4Dt/Yr+nj8iGxk8P9Y0xzQ55EAR77SJs7fTQQgkn4q6S8IwP7+5Xwu4wljMrBO+ffFlj2Cs7NREsqQxCyLEdOzBzOCu6FkxcwNkz93Zfi2CMkPFSOd8GQhppAkBT3VjnyJSdtkpyiLdTaqkHIwpaEstbNrjCjwxflNilXHp+oyY4ewQ6CvPa8taTvbaC+bsRHFL94SpXjz2buIpIEV/gmTHv1i6jf90t1cuAqmd2U8FjCu43cJXcqpcPUtbgVJTr/N1Fj42LgJ1GHGEqF+9Z45T2yPT/VbDlGM2y4WBN8rC3oR7MMHHBjvb+PMImDVmeGg=
  app:
    dev: kolicalc
  skip_cleanup: true